/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAttemptsRouteImport } from './routes/_authenticated/attempts'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as LegalDocSlugRouteImport } from './routes/legal/$docSlug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAttemptAttemptIdRouteImport } from './routes/_authenticated/attempt.$attemptId'
import { Route as AuthenticatedOrganizationBrandingRouteImport } from './routes/_authenticated/organization.branding'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedReviewAttemptIdRouteImport } from './routes/_authenticated/review.$attemptId'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin/index'
import { Route as AuthenticatedAdminAdminAiRouteImport } from './routes/_authenticated/_admin/admin/ai'
import { Route as AuthenticatedAdminAdminAuditRouteImport } from './routes/_authenticated/_admin/admin/audit'
import { Route as AuthenticatedAdminAdminBillingRouteImport } from './routes/_authenticated/_admin/admin/billing'
import { Route as AuthenticatedAdminAdminBlueprintsRouteImport } from './routes/_authenticated/_admin/admin/blueprints'
import { Route as AuthenticatedAdminAdminCertificationsRouteImport } from './routes/_authenticated/_admin/admin/certifications'
import { Route as AuthenticatedAdminAdminDocumentsRouteImport } from './routes/_authenticated/_admin/admin/documents'
import { Route as AuthenticatedAdminAdminDomainsRouteImport } from './routes/_authenticated/_admin/admin/domains'
import { Route as AuthenticatedAdminAdminExamsRouteImport } from './routes/_authenticated/_admin/admin/exams'
import { Route as AuthenticatedAdminAdminImportRouteImport } from './routes/_authenticated/_admin/admin/import'
import { Route as AuthenticatedAdminAdminOrganizationsRouteImport } from './routes/_authenticated/_admin/admin/organizations'
import { Route as AuthenticatedAdminAdminPrivacyRouteImport } from './routes/_authenticated/_admin/admin/privacy'
import { Route as AuthenticatedAdminAdminQuestionsRouteImport } from './routes/_authenticated/_admin/admin/questions'
import { Route as AuthenticatedAdminAdminReadinessRouteImport } from './routes/_authenticated/_admin/admin/readiness'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated/_admin/admin/settings'
import { Route as AuthenticatedAdminAdminStudentsRouteImport } from './routes/_authenticated/_admin/admin/students'
import { Route as AuthenticatedAdminAdminTopicsRouteImport } from './routes/_authenticated/_admin/admin/topics'
import { Route as AuthenticatedAdminInternalDesignSystemRouteImport } from './routes/_authenticated/_admin/internal.design-system'
import { Route as AuthenticatedExamsExamIdStartRouteImport } from './routes/_authenticated/exams_.$examId.start'
import { Route as ApiPublicHooksQueueWorkerRouteImport } from './routes/api/public/hooks/queue-worker'
import { Route as ApiPublicV1MembersRouteImport } from './routes/api/public/v1/members'
import { Route as ApiPublicV1OrganizationRouteImport } from './routes/api/public/v1/organization'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as AuthenticatedAdminAdminAiGeneratorRouteImport } from './routes/_authenticated/_admin/admin/ai.generator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttemptsRoute = AuthenticatedAttemptsRouteImport.update({
  id: '/attempts',
  path: '/attempts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalDocSlugRoute = LegalDocSlugRouteImport.update({
  id: '/legal/$docSlug',
  path: '/legal/$docSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAttemptAttemptIdRoute =
  AuthenticatedAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationBrandingRoute =
  AuthenticatedOrganizationBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewAttemptIdRoute =
  AuthenticatedReviewAttemptIdRouteImport.update({
    id: '/review/$attemptId',
    path: '/review/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAiRoute =
  AuthenticatedAdminAdminAiRouteImport.update({
    id: '/admin/ai',
    path: '/admin/ai',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAuditRoute =
  AuthenticatedAdminAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBillingRoute =
  AuthenticatedAdminAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBlueprintsRoute =
  AuthenticatedAdminAdminBlueprintsRouteImport.update({
    id: '/admin/blueprints',
    path: '/admin/blueprints',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminCertificationsRoute =
  AuthenticatedAdminAdminCertificationsRouteImport.update({
    id: '/admin/certifications',
    path: '/admin/certifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDocumentsRoute =
  AuthenticatedAdminAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDomainsRoute =
  AuthenticatedAdminAdminDomainsRouteImport.update({
    id: '/admin/domains',
    path: '/admin/domains',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminExamsRoute =
  AuthenticatedAdminAdminExamsRouteImport.update({
    id: '/admin/exams',
    path: '/admin/exams',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminImportRoute =
  AuthenticatedAdminAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrganizationsRoute =
  AuthenticatedAdminAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminPrivacyRoute =
  AuthenticatedAdminAdminPrivacyRouteImport.update({
    id: '/admin/privacy',
    path: '/admin/privacy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminQuestionsRoute =
  AuthenticatedAdminAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminReadinessRoute =
  AuthenticatedAdminAdminReadinessRouteImport.update({
    id: '/admin/readiness',
    path: '/admin/readiness',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminStudentsRoute =
  AuthenticatedAdminAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminTopicsRoute =
  AuthenticatedAdminAdminTopicsRouteImport.update({
    id: '/admin/topics',
    path: '/admin/topics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInternalDesignSystemRoute =
  AuthenticatedAdminInternalDesignSystemRouteImport.update({
    id: '/internal/design-system',
    path: '/internal/design-system',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedExamsExamIdStartRoute =
  AuthenticatedExamsExamIdStartRouteImport.update({
    id: '/exams_/$examId/start',
    path: '/exams/$examId/start',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksQueueWorkerRoute =
  ApiPublicHooksQueueWorkerRouteImport.update({
    id: '/api/public/hooks/queue-worker',
    path: '/api/public/hooks/queue-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MembersRoute = ApiPublicV1MembersRouteImport.update({
  id: '/api/public/v1/members',
  path: '/api/public/v1/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrganizationRoute = ApiPublicV1OrganizationRouteImport.update({
  id: '/api/public/v1/organization',
  path: '/api/public/v1/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminAiGeneratorRoute =
  AuthenticatedAdminAdminAiGeneratorRouteImport.update({
    id: '/generator',
    path: '/generator',
    getParentRoute: () => AuthenticatedAdminAdminAiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certifications': typeof CertificationsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attempts': typeof AuthenticatedAttemptsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/study': typeof AuthenticatedStudyRoute
  '/legal/$docSlug': typeof LegalDocSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/organization/branding': typeof AuthenticatedOrganizationBrandingRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/admin/ai': typeof AuthenticatedAdminAdminAiRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminAdminBillingRoute
  '/admin/blueprints': typeof AuthenticatedAdminAdminBlueprintsRoute
  '/admin/certifications': typeof AuthenticatedAdminAdminCertificationsRoute
  '/admin/documents': typeof AuthenticatedAdminAdminDocumentsRoute
  '/admin/domains': typeof AuthenticatedAdminAdminDomainsRoute
  '/admin/exams': typeof AuthenticatedAdminAdminExamsRoute
  '/admin/import': typeof AuthenticatedAdminAdminImportRoute
  '/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/admin/privacy': typeof AuthenticatedAdminAdminPrivacyRoute
  '/admin/questions': typeof AuthenticatedAdminAdminQuestionsRoute
  '/admin/readiness': typeof AuthenticatedAdminAdminReadinessRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminAdminStudentsRoute
  '/admin/topics': typeof AuthenticatedAdminAdminTopicsRoute
  '/internal/design-system': typeof AuthenticatedAdminInternalDesignSystemRoute
  '/exams/$examId/start': typeof AuthenticatedExamsExamIdStartRoute
  '/api/public/hooks/queue-worker': typeof ApiPublicHooksQueueWorkerRoute
  '/api/public/v1/members': typeof ApiPublicV1MembersRoute
  '/api/public/v1/organization': typeof ApiPublicV1OrganizationRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/ai/generator': typeof AuthenticatedAdminAdminAiGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certifications': typeof CertificationsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attempts': typeof AuthenticatedAttemptsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/study': typeof AuthenticatedStudyRoute
  '/legal/$docSlug': typeof LegalDocSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/organization/branding': typeof AuthenticatedOrganizationBrandingRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/admin/ai': typeof AuthenticatedAdminAdminAiRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminAdminBillingRoute
  '/admin/blueprints': typeof AuthenticatedAdminAdminBlueprintsRoute
  '/admin/certifications': typeof AuthenticatedAdminAdminCertificationsRoute
  '/admin/documents': typeof AuthenticatedAdminAdminDocumentsRoute
  '/admin/domains': typeof AuthenticatedAdminAdminDomainsRoute
  '/admin/exams': typeof AuthenticatedAdminAdminExamsRoute
  '/admin/import': typeof AuthenticatedAdminAdminImportRoute
  '/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/admin/privacy': typeof AuthenticatedAdminAdminPrivacyRoute
  '/admin/questions': typeof AuthenticatedAdminAdminQuestionsRoute
  '/admin/readiness': typeof AuthenticatedAdminAdminReadinessRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminAdminStudentsRoute
  '/admin/topics': typeof AuthenticatedAdminAdminTopicsRoute
  '/internal/design-system': typeof AuthenticatedAdminInternalDesignSystemRoute
  '/exams/$examId/start': typeof AuthenticatedExamsExamIdStartRoute
  '/api/public/hooks/queue-worker': typeof ApiPublicHooksQueueWorkerRoute
  '/api/public/v1/members': typeof ApiPublicV1MembersRoute
  '/api/public/v1/organization': typeof ApiPublicV1OrganizationRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/ai/generator': typeof AuthenticatedAdminAdminAiGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certifications': typeof CertificationsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/attempts': typeof AuthenticatedAttemptsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/legal/$docSlug': typeof LegalDocSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/_authenticated/organization/branding': typeof AuthenticatedOrganizationBrandingRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/_authenticated/_admin/admin/ai': typeof AuthenticatedAdminAdminAiRouteWithChildren
  '/_authenticated/_admin/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/_authenticated/_admin/admin/billing': typeof AuthenticatedAdminAdminBillingRoute
  '/_authenticated/_admin/admin/blueprints': typeof AuthenticatedAdminAdminBlueprintsRoute
  '/_authenticated/_admin/admin/certifications': typeof AuthenticatedAdminAdminCertificationsRoute
  '/_authenticated/_admin/admin/documents': typeof AuthenticatedAdminAdminDocumentsRoute
  '/_authenticated/_admin/admin/domains': typeof AuthenticatedAdminAdminDomainsRoute
  '/_authenticated/_admin/admin/exams': typeof AuthenticatedAdminAdminExamsRoute
  '/_authenticated/_admin/admin/import': typeof AuthenticatedAdminAdminImportRoute
  '/_authenticated/_admin/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/_authenticated/_admin/admin/privacy': typeof AuthenticatedAdminAdminPrivacyRoute
  '/_authenticated/_admin/admin/questions': typeof AuthenticatedAdminAdminQuestionsRoute
  '/_authenticated/_admin/admin/readiness': typeof AuthenticatedAdminAdminReadinessRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/_authenticated/_admin/admin/students': typeof AuthenticatedAdminAdminStudentsRoute
  '/_authenticated/_admin/admin/topics': typeof AuthenticatedAdminAdminTopicsRoute
  '/_authenticated/_admin/internal/design-system': typeof AuthenticatedAdminInternalDesignSystemRoute
  '/_authenticated/exams_/$examId/start': typeof AuthenticatedExamsExamIdStartRoute
  '/api/public/hooks/queue-worker': typeof ApiPublicHooksQueueWorkerRoute
  '/api/public/v1/members': typeof ApiPublicV1MembersRoute
  '/api/public/v1/organization': typeof ApiPublicV1OrganizationRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/ai/generator': typeof AuthenticatedAdminAdminAiGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/certifications'
    | '/forgot-password'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attempts'
    | '/billing'
    | '/dashboard'
    | '/exams'
    | '/help'
    | '/interview'
    | '/organization'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/study'
    | '/legal/$docSlug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/attempt/$attemptId'
    | '/organization/branding'
    | '/results/$attemptId'
    | '/review/$attemptId'
    | '/api/public/health'
    | '/api/public/telemetry'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/blueprints'
    | '/admin/certifications'
    | '/admin/documents'
    | '/admin/domains'
    | '/admin/exams'
    | '/admin/import'
    | '/admin/organizations'
    | '/admin/privacy'
    | '/admin/questions'
    | '/admin/readiness'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/topics'
    | '/internal/design-system'
    | '/exams/$examId/start'
    | '/api/public/hooks/queue-worker'
    | '/api/public/v1/members'
    | '/api/public/v1/organization'
    | '/api/public/webhooks/razorpay'
    | '/admin/'
    | '/admin/ai/generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/certifications'
    | '/forgot-password'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attempts'
    | '/billing'
    | '/dashboard'
    | '/exams'
    | '/help'
    | '/interview'
    | '/organization'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/study'
    | '/legal/$docSlug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/attempt/$attemptId'
    | '/organization/branding'
    | '/results/$attemptId'
    | '/review/$attemptId'
    | '/api/public/health'
    | '/api/public/telemetry'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/blueprints'
    | '/admin/certifications'
    | '/admin/documents'
    | '/admin/domains'
    | '/admin/exams'
    | '/admin/import'
    | '/admin/organizations'
    | '/admin/privacy'
    | '/admin/questions'
    | '/admin/readiness'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/topics'
    | '/internal/design-system'
    | '/exams/$examId/start'
    | '/api/public/hooks/queue-worker'
    | '/api/public/v1/members'
    | '/api/public/v1/organization'
    | '/api/public/webhooks/razorpay'
    | '/admin'
    | '/admin/ai/generator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/certifications'
    | '/forgot-password'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/_admin'
    | '/_authenticated/attempts'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/help'
    | '/_authenticated/interview'
    | '/_authenticated/organization'
    | '/_authenticated/privacy'
    | '/_authenticated/profile'
    | '/_authenticated/resources'
    | '/_authenticated/study'
    | '/legal/$docSlug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/attempt/$attemptId'
    | '/_authenticated/organization/branding'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/review/$attemptId'
    | '/api/public/health'
    | '/api/public/telemetry'
    | '/_authenticated/_admin/admin/ai'
    | '/_authenticated/_admin/admin/audit'
    | '/_authenticated/_admin/admin/billing'
    | '/_authenticated/_admin/admin/blueprints'
    | '/_authenticated/_admin/admin/certifications'
    | '/_authenticated/_admin/admin/documents'
    | '/_authenticated/_admin/admin/domains'
    | '/_authenticated/_admin/admin/exams'
    | '/_authenticated/_admin/admin/import'
    | '/_authenticated/_admin/admin/organizations'
    | '/_authenticated/_admin/admin/privacy'
    | '/_authenticated/_admin/admin/questions'
    | '/_authenticated/_admin/admin/readiness'
    | '/_authenticated/_admin/admin/settings'
    | '/_authenticated/_admin/admin/students'
    | '/_authenticated/_admin/admin/topics'
    | '/_authenticated/_admin/internal/design-system'
    | '/_authenticated/exams_/$examId/start'
    | '/api/public/hooks/queue-worker'
    | '/api/public/v1/members'
    | '/api/public/v1/organization'
    | '/api/public/webhooks/razorpay'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/ai/generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CertificationsRoute: typeof CertificationsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LegalDocSlugRoute: typeof LegalDocSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
  ApiPublicHooksQueueWorkerRoute: typeof ApiPublicHooksQueueWorkerRoute
  ApiPublicV1MembersRoute: typeof ApiPublicV1MembersRoute
  ApiPublicV1OrganizationRoute: typeof ApiPublicV1OrganizationRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempts': {
      id: '/_authenticated/attempts'
      path: '/attempts'
      fullPath: '/attempts'
      preLoaderRoute: typeof AuthenticatedAttemptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/$docSlug': {
      id: '/legal/$docSlug'
      path: '/legal/$docSlug'
      fullPath: '/legal/$docSlug'
      preLoaderRoute: typeof LegalDocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attempt/$attemptId': {
      id: '/_authenticated/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization/branding': {
      id: '/_authenticated/organization/branding'
      path: '/branding'
      fullPath: '/organization/branding'
      preLoaderRoute: typeof AuthenticatedOrganizationBrandingRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$attemptId': {
      id: '/_authenticated/review/$attemptId'
      path: '/review/$attemptId'
      fullPath: '/review/$attemptId'
      preLoaderRoute: typeof AuthenticatedReviewAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ai': {
      id: '/_authenticated/_admin/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/audit': {
      id: '/_authenticated/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/billing': {
      id: '/_authenticated/_admin/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/blueprints': {
      id: '/_authenticated/_admin/admin/blueprints'
      path: '/admin/blueprints'
      fullPath: '/admin/blueprints'
      preLoaderRoute: typeof AuthenticatedAdminAdminBlueprintsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/certifications': {
      id: '/_authenticated/_admin/admin/certifications'
      path: '/admin/certifications'
      fullPath: '/admin/certifications'
      preLoaderRoute: typeof AuthenticatedAdminAdminCertificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/documents': {
      id: '/_authenticated/_admin/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/domains': {
      id: '/_authenticated/_admin/admin/domains'
      path: '/admin/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/exams': {
      id: '/_authenticated/_admin/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/import': {
      id: '/_authenticated/_admin/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/organizations': {
      id: '/_authenticated/_admin/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/privacy': {
      id: '/_authenticated/_admin/admin/privacy'
      path: '/admin/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AuthenticatedAdminAdminPrivacyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/questions': {
      id: '/_authenticated/_admin/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/readiness': {
      id: '/_authenticated/_admin/admin/readiness'
      path: '/admin/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AuthenticatedAdminAdminReadinessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/students': {
      id: '/_authenticated/_admin/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/topics': {
      id: '/_authenticated/_admin/admin/topics'
      path: '/admin/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/internal/design-system': {
      id: '/_authenticated/_admin/internal/design-system'
      path: '/internal/design-system'
      fullPath: '/internal/design-system'
      preLoaderRoute: typeof AuthenticatedAdminInternalDesignSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/exams_/$examId/start': {
      id: '/_authenticated/exams_/$examId/start'
      path: '/exams/$examId/start'
      fullPath: '/exams/$examId/start'
      preLoaderRoute: typeof AuthenticatedExamsExamIdStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/queue-worker': {
      id: '/api/public/hooks/queue-worker'
      path: '/api/public/hooks/queue-worker'
      fullPath: '/api/public/hooks/queue-worker'
      preLoaderRoute: typeof ApiPublicHooksQueueWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/members': {
      id: '/api/public/v1/members'
      path: '/api/public/v1/members'
      fullPath: '/api/public/v1/members'
      preLoaderRoute: typeof ApiPublicV1MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/organization': {
      id: '/api/public/v1/organization'
      path: '/api/public/v1/organization'
      fullPath: '/api/public/v1/organization'
      preLoaderRoute: typeof ApiPublicV1OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/ai/generator': {
      id: '/_authenticated/_admin/admin/ai/generator'
      path: '/generator'
      fullPath: '/admin/ai/generator'
      preLoaderRoute: typeof AuthenticatedAdminAdminAiGeneratorRouteImport
      parentRoute: typeof AuthenticatedAdminAdminAiRoute
    }
  }
}

interface AuthenticatedAdminAdminAiRouteChildren {
  AuthenticatedAdminAdminAiGeneratorRoute: typeof AuthenticatedAdminAdminAiGeneratorRoute
}

const AuthenticatedAdminAdminAiRouteChildren: AuthenticatedAdminAdminAiRouteChildren =
  {
    AuthenticatedAdminAdminAiGeneratorRoute:
      AuthenticatedAdminAdminAiGeneratorRoute,
  }

const AuthenticatedAdminAdminAiRouteWithChildren =
  AuthenticatedAdminAdminAiRoute._addFileChildren(
    AuthenticatedAdminAdminAiRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAiRoute: typeof AuthenticatedAdminAdminAiRouteWithChildren
  AuthenticatedAdminAdminAuditRoute: typeof AuthenticatedAdminAdminAuditRoute
  AuthenticatedAdminAdminBillingRoute: typeof AuthenticatedAdminAdminBillingRoute
  AuthenticatedAdminAdminBlueprintsRoute: typeof AuthenticatedAdminAdminBlueprintsRoute
  AuthenticatedAdminAdminCertificationsRoute: typeof AuthenticatedAdminAdminCertificationsRoute
  AuthenticatedAdminAdminDocumentsRoute: typeof AuthenticatedAdminAdminDocumentsRoute
  AuthenticatedAdminAdminDomainsRoute: typeof AuthenticatedAdminAdminDomainsRoute
  AuthenticatedAdminAdminExamsRoute: typeof AuthenticatedAdminAdminExamsRoute
  AuthenticatedAdminAdminImportRoute: typeof AuthenticatedAdminAdminImportRoute
  AuthenticatedAdminAdminOrganizationsRoute: typeof AuthenticatedAdminAdminOrganizationsRoute
  AuthenticatedAdminAdminPrivacyRoute: typeof AuthenticatedAdminAdminPrivacyRoute
  AuthenticatedAdminAdminQuestionsRoute: typeof AuthenticatedAdminAdminQuestionsRoute
  AuthenticatedAdminAdminReadinessRoute: typeof AuthenticatedAdminAdminReadinessRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminStudentsRoute: typeof AuthenticatedAdminAdminStudentsRoute
  AuthenticatedAdminAdminTopicsRoute: typeof AuthenticatedAdminAdminTopicsRoute
  AuthenticatedAdminInternalDesignSystemRoute: typeof AuthenticatedAdminInternalDesignSystemRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAiRoute: AuthenticatedAdminAdminAiRouteWithChildren,
  AuthenticatedAdminAdminAuditRoute: AuthenticatedAdminAdminAuditRoute,
  AuthenticatedAdminAdminBillingRoute: AuthenticatedAdminAdminBillingRoute,
  AuthenticatedAdminAdminBlueprintsRoute:
    AuthenticatedAdminAdminBlueprintsRoute,
  AuthenticatedAdminAdminCertificationsRoute:
    AuthenticatedAdminAdminCertificationsRoute,
  AuthenticatedAdminAdminDocumentsRoute: AuthenticatedAdminAdminDocumentsRoute,
  AuthenticatedAdminAdminDomainsRoute: AuthenticatedAdminAdminDomainsRoute,
  AuthenticatedAdminAdminExamsRoute: AuthenticatedAdminAdminExamsRoute,
  AuthenticatedAdminAdminImportRoute: AuthenticatedAdminAdminImportRoute,
  AuthenticatedAdminAdminOrganizationsRoute:
    AuthenticatedAdminAdminOrganizationsRoute,
  AuthenticatedAdminAdminPrivacyRoute: AuthenticatedAdminAdminPrivacyRoute,
  AuthenticatedAdminAdminQuestionsRoute: AuthenticatedAdminAdminQuestionsRoute,
  AuthenticatedAdminAdminReadinessRoute: AuthenticatedAdminAdminReadinessRoute,
  AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
  AuthenticatedAdminAdminStudentsRoute: AuthenticatedAdminAdminStudentsRoute,
  AuthenticatedAdminAdminTopicsRoute: AuthenticatedAdminAdminTopicsRoute,
  AuthenticatedAdminInternalDesignSystemRoute:
    AuthenticatedAdminInternalDesignSystemRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOrganizationRouteChildren {
  AuthenticatedOrganizationBrandingRoute: typeof AuthenticatedOrganizationBrandingRoute
}

const AuthenticatedOrganizationRouteChildren: AuthenticatedOrganizationRouteChildren =
  {
    AuthenticatedOrganizationBrandingRoute:
      AuthenticatedOrganizationBrandingRoute,
  }

const AuthenticatedOrganizationRouteWithChildren =
  AuthenticatedOrganizationRoute._addFileChildren(
    AuthenticatedOrganizationRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAttemptsRoute: typeof AuthenticatedAttemptsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRouteWithChildren
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedAttemptAttemptIdRoute: typeof AuthenticatedAttemptAttemptIdRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedReviewAttemptIdRoute: typeof AuthenticatedReviewAttemptIdRoute
  AuthenticatedExamsExamIdStartRoute: typeof AuthenticatedExamsExamIdStartRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAttemptsRoute: AuthenticatedAttemptsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRouteWithChildren,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedAttemptAttemptIdRoute: AuthenticatedAttemptAttemptIdRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedReviewAttemptIdRoute: AuthenticatedReviewAttemptIdRoute,
  AuthenticatedExamsExamIdStartRoute: AuthenticatedExamsExamIdStartRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CertificationsRoute: CertificationsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LegalDocSlugRoute: LegalDocSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
  ApiPublicHooksQueueWorkerRoute: ApiPublicHooksQueueWorkerRoute,
  ApiPublicV1MembersRoute: ApiPublicV1MembersRoute,
  ApiPublicV1OrganizationRoute: ApiPublicV1OrganizationRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
